### PR TITLE
Fix BGV ring dimension underestimation with NOISE_FLOODING_MULTIPARTY + HYBRID on 128-bit builds

### LINKED ISSUE #1157: Fix BGV ring dimension underestimation with NOISE_FLOODING_MULTIPARTY + HYBRID on 128-bit builds
src/pke/examples/threshold-fhe.cpp throws an exception:
E   RuntimeError: /home/ubuntu/actions-runners/openfhe-python/_work/openfhe-python/openfhe-python/openfhe-python-packager/build/openfhe-development/src/pke/lib/scheme/bgvrns/bgvrns-parametergeneration.cpp:l.644:ParamsGenBGVRNSInternal(): The ring dimension found using estimated logQ(P) [16384] does does not meet security requirements. Report this problem to OpenFHE developers and set the ring dimension manually to 32768.

### PR DESCRIPTION
**Pull request by dsuponitskiy**
**BUG**
We estimate P from estimated Q before the flooding primes are added. After that, the actual value of P is calculated from the actual Q in PrecomputeCRTTables(). In some 128-bit cases this made the real QP bigger than expected and failed generating a cryptocontext.

**FIXES**
* Makes the P estimate include the flooding primes (this bug affected BGV and BFV)
* Adds a check to compare estimated vs actual sizeP in PrecomputeCRTTables() and triggers an exception if there is a mismatch
* Fixes another bug (affecting FIXEDMANUAL for BGV), which was detected by the new checking mechanism. An extra bit was added to an estimate of Q for FIXEDMANUAL, which caused a mismatch in the size limbs in P.

### CODE REVIEW

File: src/pke/lib/scheme/bgvrns/bgvrns-parametergeneration.cpp [hunk 1]
```diff
@@ -490,11 +490,21 @@ bool ParameterGenerationBGVRNS::ParamsGenBGVRNSInternal(std::shared_ptr<CryptoPa
...
+                uint32_t numPrimesEst = (scalTech == FLEXIBLEAUTOEXT) ? moduliQ.size() - 1 : moduliQ.size();
+                double dcrtBitsEst    = (moduliQ.size() > 1) ? std::log2(moduliQ[1].ConvertToDouble()) : 0;
+                if (multipartyMode == NOISE_FLOODING_MULTIPARTY) {
+                    numPrimesEst += NoiseFlooding::NUM_MODULI_MULTIPARTY;
+                    dcrtBitsEst = std::max(dcrtBitsEst, static_cast<double>(NoiseFlooding::MULTIPARTY_MOD_SIZE));
+                }
                 auto hybridKSInfo = CryptoParametersRNS::EstimateLogP(
                     numPartQ, std::log2(moduliQ[0].ConvertToDouble()),
-                    (moduliQ.size() > 1) ? std::log2(moduliQ[1].ConvertToDouble()) : 0,
+                    dcrtBitsEst,
```
Comment (yspolyakov) [inline src/pke/lib/scheme/bgvrns/bgvrns-parametergeneration.cpp:508]: The fix is wrong. It will use MULTIPARTY_MOD_SIZE (60 bits for NATIVEINT=64) for all RNS moduli, which will overestimate logQP.

Comment (yspolyakov) [reply src/pke/lib/scheme/bgvrns/bgvrns-parametergeneration.cpp:508]: dcrtBitsEst should not be changed!

File: src/pke/lib/scheme/bgvrns/bgvrns-parametergeneration.cpp [hunk 2]
```diff
@@ -490,11 +490,21 @@ bool ParameterGenerationBGVRNS::ParamsGenBGVRNSInternal(std::shared_ptr<CryptoPa
...
+                // flooding primes (of MULTIPARTY_MOD_SIZE bits each) to Q after this loop. Include them
+                // in the P estimation so the ring dimension is not underestimated, particularly in
+                // 128-bit builds where P primes are 121 bits and the larger QP can exceed the security limit.
+                uint32_t numPrimesEst = (scalTech == FLEXIBLEAUTOEXT) ? moduliQ.size() - 1 : moduliQ.size();
+                double dcrtBitsEst    = (moduliQ.size() > 1) ? std::log2(moduliQ[1].ConvertToDouble()) : 0;
+                if (multipartyMode == NOISE_FLOODING_MULTIPARTY) {
+                    numPrimesEst += NoiseFlooding::NUM_MODULI_MULTIPARTY;
+                    dcrtBitsEst = std::max(dcrtBitsEst, static_cast<double>(NoiseFlooding::MULTIPARTY_MOD_SIZE));
+                }
                 auto hybridKSInfo = CryptoParametersRNS::EstimateLogP(
```
Comment (yspolyakov) [inline src/pke/lib/scheme/bgvrns/bgvrns-parametergeneration.cpp:506]: We should extend the API for EstimateLogP to pass the flag for NOISE_FLOODING_MULTIPARTY (which mode). If it is set, then the first NoiseFlooding::NUM_MODULI_MULTIPARTY moduli should be set to NoiseFlooding::MULTIPARTY_MOD_SIZE inside the code for EstimateLogP.

File: src/pke/include/schemerns/rns-cryptoparameters.h [hunk 3]
```diff
@@ -195,13 +195,15 @@ class CryptoParametersRNS : public CryptoParametersRLWE<DCRTPoly> {
    * @param numPrimes number of moduli witout extraModulus
    * @param auxBits size of auxiliar moduli used for hybrid key switching
    * @param scalTech scaling technique
+   * @param isNoiseFloodingMultiparty whether threshold FHE uses noise flooding multiparty mode (BGV only)
```
Comment (yspolyakov) [inline src/pke/include/schemerns/rns-cryptoparameters.h]: BFV as well

File: src/pke/include/schemerns/rns-cryptoparameters.h [hunk 4]
```diff
@@ -195,13 +195,15 @@ class CryptoParametersRNS : public CryptoParametersRLWE<DCRTPoly> {
...
    * @param addOne should an extra bit be added (for CKKS and BGV)
    *
    * @return log2 of the modulus and number of RNS limbs.
    */
     static std::pair<double, uint32_t> EstimateLogP(uint32_t numPartQ, double firstModulusSize, double dcrtBits,
                                                     double extraModulusSize, uint32_t numPrimes, uint32_t auxBits,
-                                                    ScalingTechnique scalTech, bool addOne = false);
+                                                    ScalingTechnique scalTech, bool isNoiseFloodingMultiparty = false,
+                                                    bool addOne = false);
```
Comment (yspolyakov) [inline src/pke/include/schemerns/rns-cryptoparameters.h]: Add isNoiseFloodingMultiparty last

File: src/pke/lib/schemerns/rns-cryptoparameters.cpp [hunk 5]
```diff
@@ -419,6 +420,11 @@ std::pair<double, uint32_t> CryptoParametersRNS::EstimateLogP(uint32_t numPartQ,
     qi[0] = firstModulusSize;
     if (extraModulusSize > 0)
         qi[sizeQ - 1] = extraModulusSize;
+    if (isNoiseFloodingMultiparty) {
+        for (size_t i = 0; i < std::min<size_t>(NoiseFlooding::NUM_MODULI_MULTIPARTY, sizeQ); ++i) {
```
Comment (yspolyakov) [inline src/pke/lib/schemerns/rns-cryptoparameters.cpp]: It should start with index 1, not 0. Otherwise, you will overwrite the first modulus, leading to errors.

Comment (yspolyakov) [inline src/pke/lib/schemerns/rns-cryptoparameters.cpp]: Another change: "i < std::min<size_t>(NoiseFlooding::NUM_MODULI_MULTIPARTY, sizeQ)" should be replaced with "i < NoiseFlooding::NUM_MODULI_MULTIPARTY + 1"

**Review by yspolyakov — APPROVED** [review]
