### PR TITLE
adjust plaintext modulus for large precision scheme switching

### LINKED ISSUE #1092: Investigate intermittent Scheme Switching failure
Example 1:

[ RUN      ] UnitTests/UTCKKSRNS_SCHEMESWITCH.CKKSRNS/SCHEME_SWITCH_FHEW_CKKS_05
/home/ubuntu/actions-runner/_work/openfhe-development/openfhe-development/src/pke/unittest/utils/UnitTestUtils.h:116: Failure
Value of: checkEquality(a, b, eps)
  Actual: false
Expected: true
SCHEME_SWITCH_FHEW_CKKS_05FHEW to CKKS fails for larger messages.

[  FAILED  ] UnitTests/UTCKKSRNS_SCHEMESWITCH.CKKSRNS/SCHEME_SWITCH_FHEW_CKKS_05, where GetParam() = testCaseType [SCHEME_SWITCH_FHEW_CKKS], schemeId [CKKSRNS], ringDimension [64], multiplicativeDepth [13], scalingModSize [50], digitSize [-999], batchSize [-999], secretKeyDist [2], maxRelinSkDeg [-999], firstModSize [60], securityLevel [6], ksTech [2], scalTech [1], numLargeDigits [3], plaintextModulus [-999], standardDeviation [-999], evalAddCount [-999], keySwitchCount [-999], multiplicationTechnique [-999], encryptionTechnique [-999], PREMode [-999], multipartyMode [-999], decryptionNoiseMode [-999], executionMode [-999], noiseEstimate [-999], registerWordSize [-999], compositeDegree [-999]  (268 ms)

Example 2:

[ RUN      ] UnitTests/UTCKKSRNS_SCHEMESWITCH.CKKSRNS/SCHEME_SWITCH_FHEW_CKKS_01
/home/ubuntu/actions-runner/_work/openfhe-development/openfhe-development/src/pke/unittest/utils/UnitTestUtils.h:116: Failure
Value of: checkEquality(a, b, eps)
  Actual: false
Expected: true
SCHEME_SWITCH_FHEW_CKKS_01FHEW to CKKS fails for larger messages.

[  FAILED  ] UnitTests/UTCKKSRNS_SCHEMESWITCH.CKKSRNS/SCHEME_SWITCH_FHEW_CKKS_01, where GetParam() = testCaseType [SCHEME_SWITCH_FHEW_CKKS], schemeId [CKKSRNS], ringDimension [64], multiplicativeDepth [13], scalingModSize [70], digitSize [-999], batchSize [-999], secretKeyDist [1], maxRelinSkDeg [-999], firstModSize [80], securityLevel [6], ksTech [2], scalTech [1], numLargeDigits [3], plaintextModulus [-999], standardDeviation [-999], evalAddCount [-999], keySwitchCount [-999], multiplicationTechnique [-999], encryptionTechnique [-999], PREMode [-999], multipartyMode [-999], decryptionNoiseMode [-999], executionMode [-999], noiseEstimate [-999], registerWordSize [-999], compositeDegree [-999]  (1706 ms)

Connected to #1098 and potentially fixed by #1099.

### PR DESCRIPTION
**Pull request by pascoec**
* Corrected the value of plaintext modulus in unit tests and examples for the cases when large precision is sought during FHEW to CKKS switching
* Added more clarifications to the documentation for FHEW<->CKKS scheme switching and more comments to the examples

### CODE REVIEW

File: src/pke/examples/scheme-switching.cpp [hunk 1]
```diff
@@ -308,6 +305,19 @@ void SwitchFHEWtoCKKS() {
         x2.insert(x2.end(), zeros.begin(), zeros.end());
     }
 
+    uint32_t modulus_LWE = 1 << logQ_ccLWE;
+
+    uint32_t pLWE1 = ccLWE->GetMaxPlaintextSpace().ConvertToInt();  // Small precision
+    uint32_t pLWE2 = 256;                                           // Medium precision
+
+    // Messages encoded as [0000000MMMMM0000000EEEEE]
+    // Number of leading zeros determined by the ratio of ciphertext modulus to plaintext modulus
```
Comment (yspolyakov) [inline src/pke/examples/scheme-switching.cpp]: Typically, we need close to 10 bits to get good accuracy for sin(x) ~ x in the approximation of mod x using sin x in CKKS bootstrapping.

File: src/pke/examples/scheme-switching.cpp [hunk 2]
```diff
@@ -308,6 +305,19 @@ void SwitchFHEWtoCKKS() {
...
+    // Number of zeros between message and error determined by the ratio of plaintext modulus to magnitude of max value in message
```
Comment (yspolyakov) [inline src/pke/examples/scheme-switching.cpp]: In the fresh LWE ciphertexts, we need a gap between the message and error to be large enough for the message to be rounded correctly even after leveled computations in the linear transformation before evaluating sin(x).

File: src/pke/examples/scheme-switching.cpp [hunk 3]
```diff
@@ -308,6 +305,19 @@ void SwitchFHEWtoCKKS() {
...
+    // For correct CKKS decryption, the message magnitude should be much smaller than the plaintext modulus and the plaintext modulus should be much smaller than the ciphertext modulus
```
Comment (yspolyakov) [inline src/pke/examples/scheme-switching.cpp]: The high level idea is to have enough 0's both before the message and after the message for the CKKS-bootstrapped result to achieve reasonable accuracy.

File: src/pke/examples/scheme-switching.cpp [hunk 4]
```diff
@@ -321,6 +331,7 @@ void SwitchFHEWtoCKKS() {
         ctxtsLWE2[i] = ccLWE->Encrypt(lwesk, x1[i], LARGE_DIM, pLWE1);
     }
 
+    // Here, ratio between plaintext modulus and message magnitude is small
```
Comment (yspolyakov) [inline src/pke/examples/scheme-switching.cpp]: As a result, the error is higher.

File: src/pke/examples/scheme-switching.cpp
Comment (yspolyakov) [inline src/pke/examples/scheme-switching.cpp:341]: In this case,. the gap is larger, and better accuracy is achieved.

**Review by andreea-alexandru — APPROVED** [review]
Looks good, has all the changes we discussed.

**Review by yspolyakov — APPROVED** [review]
