### PR TITLE
isssue1147

### LINKED ISSUE #1147: Some of BFV EvalAdd/Sub* procedures produce incorrect results when ciphertexts have mismatched DCRTPoly formats (EVALUATION vs COEFFICIENT)
See https://openfhe.discourse.group/t/bug-report-bfv-evaladd-produces-incorrect-results-when-ciphertexts-have-mismatched-dcrtpoly-formats-evaluation-vs-coefficient/2304 for more details

### PR DESCRIPTION
**Pull request by pascoec**
Added checks and conversions to
1. EvalAddInPlace
2. EvalSubInPlace
3. EvalMultInPlace for ciphertext and plaintext

### CODE REVIEW

File: src/pke/lib/schemebase/base-leveledshe.cpp [hunk 1]
```diff
@@ -172,10 +182,16 @@ Ciphertext<Element> LeveledSHEBase<Element>::EvalMult(ConstCiphertext<Element>&
 
 template <class Element>
 void LeveledSHEBase<Element>::EvalMultInPlace(Ciphertext<Element>& ciphertext, ConstPlaintext& plaintext) const {
-    auto pt = plaintext->GetElement<Element>();
-    pt.SetFormat(Format::EVALUATION);
-    for (auto& c : ciphertext->GetElements())
-        c *= pt;
+    if (plaintext->GetElement<Element>().GetFormat() == Format::EVALUATION) {
```
Comment (yspolyakov) [inline src/pke/lib/schemebase/base-leveledshe.cpp:185]: What if the ciphertext is in the COEFFICIENT representation and plaintext in the EVALUATION representation?

Comment (pascoec) [reply src/pke/lib/schemebase/base-leveledshe.cpp:185]: Then line 187 will throw an error

Comment (yspolyakov) [reply src/pke/lib/schemebase/base-leveledshe.cpp:185]: It seems like the logic is different from Add/Sub. In my mind, it should check whether both of them are in EVALUATION, adjust if needed, and then do the multiplication

**Review by yspolyakov — APPROVED** [review]
