### PR TITLE
Fixed the inconsistency in the minimum value of scaling mod size

### LINKED ISSUE #1133: Inconsistency in the minimum value of scaling mod size for CKKS
See https://openfhe.discourse.group/t/inconsistent-minimum-value-for-scalingmodsize/2278 for more details.

===========================================================================================
Solution:
1. DCRT_MODULUS::MIN_SIZE stays 14
2. Correct all relevant conditions and error messages to use DCRT_MODULUS::MIN_SIZE/DCRT_MODULUS::MAX_SIZE instead of hardcoded numbers

### PR DESCRIPTION
**Pull request by dsuponitskiy**
1. Moved the DCRT_MODULUS enum from "ParameterGenerationRNS" to a new header.
2. Replaced hardcoded values in error messages with DCRT_MODULUS::MIN_SIZE and DCRT_MODULUS::MAX_SIZE

### CODE REVIEW

File: src/pke/lib/scheme/bgvrns/bgvrns-parametergeneration.cpp [hunk 1]
```diff
@@ -195,9 +195,8 @@ std::pair<std::vector<NativeInteger>, uint32_t> ParameterGenerationBGVRNS::compu
         firstModLowerBound = 2.0 * plainModulus * noiseEstimates.noisePerLevel - plainModulus;
     uint32_t firstModSize = std::ceil(std::log2(firstModLowerBound));
     if (firstModSize >= DCRT_MODULUS::MAX_SIZE) {
-        OPENFHE_THROW(
-            "Change parameters! Try reducing the number of additions per level, "
-            "number of key switches per level, or the digit size. We cannot support moduli greater than 60 bits.");
+        OPENFHE_THROW(std::string("Reduce the number of additions or key switches per level or the digit size. ") +
+            "We do not support moduli greater than " + std::to_string(DCRT_MODULUS::MAX_SIZE-1) + " bits.");
```
Comment (yspolyakov) [inline src/pke/lib/scheme/bgvrns/bgvrns-parametergeneration.cpp]: Should be DCRT_MODULUS::MAX_SIZE not DCRT_MODULUS::MAX_SIZE-1. Here, it has to be 59 because we use FirstPrime after this (making it 60 bits).

File: src/pke/lib/scheme/bgvrns/bgvrns-parametergeneration.cpp [hunk 2]
```diff
@@ -210,9 +209,8 @@ std::pair<std::vector<NativeInteger>, uint32_t> ParameterGenerationBGVRNS::compu
         uint32_t extraModSize = std::ceil(std::log2(extraModLowerBound));
 
         if (extraModSize >= DCRT_MODULUS::MAX_SIZE) {
-            OPENFHE_THROW(
-                "Change parameters! Try reducing the number of additions per level, "
-                "number of key switches per level, or the digit size. We cannot support moduli greater than 60 bits.");
+            OPENFHE_THROW(std::string("Reduce the number of additions or key switches per level or the digit size. ") +
+                "We do not support moduli greater than " + std::to_string(DCRT_MODULUS::MAX_SIZE-1) + " bits.");
```
Comment (yspolyakov) [inline src/pke/lib/scheme/bgvrns/bgvrns-parametergeneration.cpp]: Ditto

File: src/pke/lib/scheme/bgvrns/bgvrns-parametergeneration.cpp [hunk 3]
```diff
@@ -242,9 +240,8 @@ std::pair<std::vector<NativeInteger>, uint32_t> ParameterGenerationBGVRNS::compu
 
         uint32_t modSize = std::ceil(std::log2(modLowerBound));
         if (modSize >= DCRT_MODULUS::MAX_SIZE) {
-            OPENFHE_THROW(
-                "Change parameters! Try reducing the number of additions per level, "
-                "number of key switches per level, or the digit size. We cannot support moduli greater than 60 bits.");
+            OPENFHE_THROW(std::string("Reduce the number of additions or key switches per level or the digit size. ") +
+                "We do not support moduli greater than " + std::to_string(DCRT_MODULUS::MAX_SIZE-1) + " bits.");
```
Comment (yspolyakov) [inline src/pke/lib/scheme/bgvrns/bgvrns-parametergeneration.cpp]: Ditto

File: src/pke/lib/scheme/gen-cryptocontext-params-validation.cpp [hunk 4]
```diff
@@ -60,18 +61,18 @@ void validateParametersForCryptocontext(const Params& parameters) {
         if (COMPOSITESCALINGAUTO == parameters.GetScalingTechnique() ||
             COMPOSITESCALINGMANUAL == parameters.GetScalingTechnique()) {
             if (COMPOSITESCALING_MAX_MODULUS_SIZE <= parameters.GetScalingModSize() ||
-                15 > parameters.GetScalingModSize()) {
-                OPENFHE_THROW("scalingModSize should be greater than 15 and less than " +
-                              std::to_string(COMPOSITESCALING_MAX_MODULUS_SIZE));
+                DCRT_MODULUS::MIN_SIZE > parameters.GetScalingModSize()) {
+                OPENFHE_THROW("scalingModSize should be greater than " + std::to_string(DCRT_MODULUS::MIN_SIZE-1) +
```
Comment (yspolyakov) [inline src/pke/lib/scheme/gen-cryptocontext-params-validation.cpp]: should be at least MIN_SIZE -> more accurate wording

File: src/pke/lib/scheme/gen-cryptocontext-params-validation.cpp [hunk 5]
```diff
@@ -60,18 +61,18 @@ void validateParametersForCryptocontext(const Params& parameters) {
...
             if (SPARSE_ENCAPSULATED == parameters.GetSecretKeyDist()) {
                 OPENFHE_THROW("SPARSE_ENCAPSULATED not yet supported with COMPOSITESCALING");
             }
         }
         else {
-            if (MAX_MODULUS_SIZE <= parameters.GetScalingModSize() || 15 > parameters.GetScalingModSize()) {
-                OPENFHE_THROW("scalingModSize should be greater than 15 and less than " +
-                              std::to_string(MAX_MODULUS_SIZE));
+            if (MAX_MODULUS_SIZE <= parameters.GetScalingModSize() || DCRT_MODULUS::MIN_SIZE > parameters.GetScalingModSize()) {
+                OPENFHE_THROW("scalingModSize should be greater than " + std::to_string(DCRT_MODULUS::MIN_SIZE-1) +
```
Comment (yspolyakov) [inline src/pke/lib/scheme/gen-cryptocontext-params-validation.cpp]: Ditto

**Review by yspolyakov — APPROVED** [review]
